server:
  port: 8082

keycloak:
  server-url: http://localhost:8081
  realm: web-store
  client-id: web-store-client
  client-secret: kVFHzOoDtuW8aB2m2CgbW6Z1hy7GYytV

services:
  user-service-url: http://users-web-store:8080/api/users