server:
  port: 8085

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  liquibase:
    change-log: db/changelog/changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/inno
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

keycloak:
  server-url: http://localhost:8081
  realm: web-store

client:
  user-service-uri: http://localhost:8080/api/users/email/{email}