version: "3.9"

services:
  keycloak:
    image: bitnami/keycloak:26.2.4
    ports:
      - "8081:8081"
      - "8443:8443"
    environment:
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HTTP_PORT: 8081
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: keycloak-postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: "keycloak"
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: --import-realm --verbose --health-enabled=true
    volumes:
      - ./keycloak/realms:/opt/bitnami/keycloak/data/import
    networks:
      - inno
    healthcheck:
      test: curl -f http://localhost:9000/health/live
      interval: 60s
      timeout: 20s
      retries: 10
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  keycloak-postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql
    networks:
      - inno
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: inno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - inno
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - inno
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: payment
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - inno
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - inno
    volumes:
      - kafka_data:/var/lib/kafka/data

  users-web-store:
    build:
      context: ../users
      dockerfile: ../users/docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  orders-web-store:
    build:
      context: ../orders
      dockerfile: ../orders/docker/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  auth-web-store:
    build:
      context: ../auth
      dockerfile: ../auth/docker/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - keycloak
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  payment-web-store:
    build:
      context: ../payment
      dockerfile: ../payment/docker/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gateway-web-store:
    build:
      context: ../gateway
      dockerfile: ../gateway/docker/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - keycloak
      - payment-web-store
      - orders-web-store
      - users-web-store
      - auth-web-store
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres-data:
  keycloak_data:
  kafka_data:
  mongo_data:

networks:
  inno: