version: "3.9"

services:
  keycloak:
    image: bitnami/keycloak:26.2.4
    ports:
      - "8081:8081"
      - "8443:8443"
    environment:
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HTTP_PORT: 8081
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: keycloak-postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: "keycloak"
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: --import-realm --verbose --health-enabled=true
    volumes:
      - ./keycloak/realms:/opt/bitnami/keycloak/data/import
    networks:
      - inno
    healthcheck:
      test: curl -f http://localhost:9000/health/live
      interval: 60s
      timeout: 20s
      retries: 10
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  keycloak-postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql
    networks:
      - inno
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: inno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - inno
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - inno
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  users-web-store:
    build:
      context: ../users
      dockerfile: ../users/docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  orders-web-store:
    build:
      context: ../orders
      dockerfile: ../orders/docker/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

  auth-web-store:
    build:
      context: ../auth
      dockerfile: ../auth/docker/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - keycloak
    networks:
      - inno
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres-data:
  keycloak_data:

networks:
  inno: