server:
  port: 8084

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://auth-web-store:8082
              predicates:
                - Path=/api/auth/**
              filters:
                - name: SignUpFilter

            - id: order
              uri: http://orders-web-store:8083
              predicates:
                - Path=/api/orders/**,/api/items/**

            - id: users
              uri: http://users-web-store:8080
              predicates:
                - Path=/api/users/**,/api/cards/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/web-store}

services:
  user-service-url: http://users-web-store:8080/api/users
  auth-service-url: http://auth-web-store:8082/api/auth