apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: inno
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_DATABASE_USER: postgres
  KEYCLOAK_DATABASE_PASSWORD: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres